import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, ListChecks, ShieldCheck, Workflow } from "lucide-react";
import { useMemo, useState } from "react";

import { Shell } from "@/components/app/Shell";
import { ActionCard, MetricCard, PageHeader, PriorityBadge } from "@/components/app/bits";
import { AGENTS, orchestrate, type Priority } from "@/lib/agents";
import { inr } from "@/lib/intelligence";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/decisions")({
  validateSearch: (search: Record<string, unknown>) => ({
    priority: typeof search.priority === "string" ? search.priority : "ALL",
  }),
  head: () => ({
    meta: [
      { title: "AI Decision Center — StockPilot AI" },
      {
        name: "description",
        content:
          "Today's prioritised inventory actions ranked by urgency, financial impact, stockout, expiry and dead-stock risk.",
      },
      { property: "og:title", content: "AI Decision Center — StockPilot AI" },
      {
        property: "og:description",
        content: "A ranked action plan generated by six inventory intelligence agents.",
      },
    ],
  }),
  component: DecisionCenter,
});

const FILTERS: (Priority | "ALL")[] = ["ALL", "CRITICAL", "HIGH", "MEDIUM", "LOW"];

function DecisionCenter() {
  const search = Route.useSearch();
  const o = useMemo(() => orchestrate(), []);
  const [filter, setFilter] = useState<Priority | "ALL">(search.priority as Priority | "ALL");

  const visible = o.findings.filter((f) => filter === "ALL" || f.priority === filter);
  const critical = o.findings.filter((f) => f.priority === "CRITICAL");
  const valueAtStake = o.findings.reduce((s, f) => s + f.impactValue, 0);

  return (
    <Shell require="ai.view">
      <PageHeader
        eyebrow="Orchestrated action plan"
        title="AI Decision Center"
        description="The Inventory Orchestrator collects findings from every specialised agent, resolves conflicting recommendations per SKU and ranks what is left by urgency, money at stake and risk type."
      />

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Critical actions" value={`${critical.length}`} sub="Execute before end of day" icon={AlertTriangle} tone="critical" />
        <MetricCard label="Total findings" value={`${o.findings.length}`} sub="After conflict resolution" icon={ListChecks} delay={60} />
        <MetricCard label="Value at stake" value={inr(valueAtStake, true)} sub="Revenue + capital protected" icon={ShieldCheck} tone="positive" delay={120} />
        <MetricCard label="Agents consulted" value={`${AGENTS.length}`} sub="Health · Forecast · Reorder · Dead · Expiry · Analytics" icon={Workflow} tone="accent" delay={180} />
      </section>

      <section className="panel animate-rise p-5">
        <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
          Orchestration trace
        </p>
        <ol className="mt-4 grid gap-3 md:grid-cols-7">
          {[
            "User question",
            "Inventory Orchestrator",
            "Specialised agents",
            "Analysis + evidence",
            "Priority engine",
            "Action plan",
            "Business owner",
          ].map((step, i) => (
            <li key={step} className="flex items-center gap-3 md:block">
              <span className="num grid size-6 shrink-0 place-items-center rounded-md bg-primary/12 text-[11px] font-semibold text-primary">
                {i + 1}
              </span>
              <p className="mt-2 text-xs font-medium text-foreground md:mt-2">{step}</p>
            </li>
          ))}
        </ol>
      </section>

      <section className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          {FILTERS.map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={cn(
                "rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors",
                filter === f
                  ? "border-primary/50 bg-primary/12 text-primary"
                  : "border-border text-muted-foreground hover:text-foreground",
              )}
            >
              {f === "ALL" ? "All priorities" : f}
              <span className="num ml-2 text-[10px] opacity-70">
                {f === "ALL" ? o.findings.length : o.findings.filter((x) => x.priority === f).length}
              </span>
            </button>
          ))}
        </div>

        <div className="panel overflow-hidden">
          <div className="border-b border-border/70 px-5 py-3.5">
            <p className="text-sm font-semibold text-foreground">Today&apos;s top actions</p>
            <p className="text-xs text-muted-foreground">
              Ranked by the priority engine: urgency (62%), financial exposure (24%), agent confidence weight (14%).
            </p>
          </div>
          <ul className="divide-y divide-border/70">
            {visible.slice(0, 5).map((f, i) => (
              <li key={f.id} className="flex flex-wrap items-center gap-3 px-5 py-3 text-sm">
                <span className="num w-5 text-xs text-muted-foreground">{i + 1}</span>
                <PriorityBadge priority={f.priority} />
                <span className="font-medium text-foreground">{f.product}</span>
                <span className="text-xs text-muted-foreground">{f.action}</span>
                <span className="num ml-auto text-xs font-semibold text-primary">{inr(f.impactValue, true)}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="grid gap-5 xl:grid-cols-2">
          {visible.map((f, i) => (
            <ActionCard key={f.id} finding={f} rank={i + 1} />
          ))}
        </div>
      </section>
    </Shell>
  );
}